### ISSUE TITLE
No ACL in the pre defined policies (after bootstrap)

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-demo#44] opened 2020-07-22 19:47 UTC

**Comment by davegarvey** [comment] 2020-08-03 01:56
I noticed that the Policies exported by the `export.sh` script do not contain all the expected data. This is something that has changed since v3. Will need further investigation.

**Comment by davegarvey** [comment] 2020-09-08 07:13
This appears to be fixed in 3.0.1

**Comment by davegarvey** [comment] 2020-09-08 08:03
Sorry, got this wrong - it's still an issue.

**Comment by davegarvey** [comment] 2020-09-09 01:56
I've raised an issue here https://tyktech.atlassian.net/browse/TT-479

I believe the problem is that the Dashboard Admin API does not import the data correctly. Am refactoring the bootstrap scripts to try to work around this.

**Closed** 2023-01-27 20:15 UTC
